---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: sort-simple-yaml
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: mixed-line-ending
      - id: fix-encoding-pragma
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: check-xml
      - id: check-vcs-permalinks
      - id: check-toml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: pretty-format-json
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: check-case-conflict
