# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
workflows:
  version: 2
  default:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build_darwin:
          filters:
            tags:
              only: /.*/
          requires: 
            - test
      - build_linux:
          filters:
            tags:
              only: /.*/
          requires: 
            - test
      - build_windows:
          filters:
            tags:
              only: /.*/
          requires: 
            - test
      - github-release:
          requires:
            - build_darwin
            - build_linux
            - build_windows
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
jobs:
  test:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/test
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v -timeout 15m ./...
  build_darwin:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GOOS: darwin
      GOARCH: amd64
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: 
          command: go build -v -o terraform-provider-device42_${GOOS}_${GOARCH}
      - persist_to_workspace:
          root: .
          paths:
            - "terraform-provider-device42_darwin_amd64"
      - store_artifacts:
          path: terraform-provider-device42_darwin_amd64
          destination: terraform-provider-device42_darwin_amd64
  build_linux:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GOOS: linux
      GOARCH: amd64
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build -v -o terraform-provider-device42_${GOOS}_${GOARCH}
      - persist_to_workspace:
          root: .
          paths:
            - "terraform-provider-device42_linux_amd64"
      - store_artifacts:
          path: terraform-provider-device42_linux_amd64
          destination: terraform-provider-device42_linux_amd64
  build_windows:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GOOS: windows
      GOARCH: amd64
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build -v -o terraform-provider-device42_${GOOS}_${GOARCH}
      - persist_to_workspace:
          root: .
          paths:
            - "terraform-provider-device42_windows_amd64"
      - store_artifacts:
          path: terraform-provider-device42_windows_amd64
          destination: terraform-provider-device42_windows_amd64
  github-release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          command: |
            ls -l ./workspace
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./workspace/